language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "hhvm"
  - "hhvm-nightly"
matrix:
  allow_failures:
    - php: "hhvm"  # need HHVM >= 3.10.0
sudo: false
env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN=1
install:
  - composer install
  - composer update --with-dependencies mediawiki/mediawiki-codesniffer phpunit/phpunit
script:
  - composer test
